
--SELECT
--	PROD.SLS_DOC_NO,
--	I_FINAL.SLS_DOC_NO,
--	PROD.DELIVERY_NO,
--	I_FINAL.DELIVERY_NO,
--	PROD.LINE_NO,
--	I_FINAL.LINE_NO,
--	PROD.ITEM_CODE,
--	I_FINAL.ITEM_CODE,
--	PROD.SHIP_QTY,
--	I_FINAL.SHIP_QTY,
--	PROD.SLS_OFFICE,
--	I_FINAL.SLS_OFFICE,
--	PROD.NET_AMOUNT,
--	I_FINAL.NET_AMOUNT,
--	PROD.RETAIL_PRICE,
--	I_FINAL.RETAIL_PRICE,
--	PROD.ITEM_COST,
--	I_FINAL.ITEM_COST,
--	PROD.PROMO_CODE,
--	I_FINAL.PROMO_CODE,
--	PROD.MTAXG_CODE,
--	I_FINAL.MTAXG_CODE,
--	PROD.DELIVERY_STATUS,
--	I_FINAL.DELIVERY_STATUS,
--	PROD.BILLING_STATUS,
--	I_FINAL.BILLING_STATUS,
--	PROD.ORDER_QTY,
--	I_FINAL.ORDER_QTY,
--	PROD.FECHAACTUALIZADO,
--	I_FINAL.FECHAACTUALIZADO,
--	PROD.CUSTOMERMATERIALNUMBER,
--	I_FINAL.CUSTOMERMATERIALNUMBER,
--	PROD.PO_LINE_NUMBER,
--	I_FINAL.PO_LINE_NUMBER,
--	PROD.DEL_LINE_NO,
--	I_FINAL.DEL_LINE_NO,
--	PROD.REJECTION,
--	I_FINAL.REJECTION,
--	PROD.TAXAMOUNT,
--	I_FINAL.TAXAMOUNT
--FROM
--	TBLORDERI_DEV_FINAL I_FINAL  
--INNER JOIN
--	TBLORDERH_DEV_FINAL H_FINAL
--ON
--	H_FINAL.SLS_DOC_NO = I_FINAL.SLS_DOC_NO
--INNER JOIN
--	[10.168.0.57].ISAP.DBO.TBLORDERI PROD
--ON	
--	I_FINAL.SLS_DOC_NO = PROD.SLS_DOC_NO
--AND
--	I_FINAL.LINE_NO = PROD.LINE_NO
--WHERE 
--	--COALESCE(PROD.item_cost,0) <> COALESCE(I_FINAL.item_cost,0)
----	COALESCE(I_FINAL.DELIVERY_NO,'') = ''
----AND
----	COALESCE(PROD.DELIVERY_NO,'') <> ''
--	PROD.billing_status	 is not null


--------------------------------------------------------------------
---ACTUALIZAR INFO FALTANTE EN TBLORDERI_DEV_FINAL CON LA INFO DE PROD, 
---CAMPOS RETAIL_PRICE, PROMO_CODE, MTAXG_CODE, DELIVERY_STATUS, BILLING_STATUS
UPDATE
	I_FINAL
SET
	I_FINAL.RETAIL_PRICE = PROD.RETAIL_PRICE,
	I_FINAL.PROMO_CODE = PROD.PROMO_CODE,
	I_FINAL.MTAXG_CODE = PROD.MTAXG_CODE,
	I_FINAL.DELIVERY_STATUS = PROD.DELIVERY_STATUS,
	I_FINAL.BILLING_STATUS = PROD.BILLING_STATUS
FROM
	TBLORDERI_DEV_FINAL I_FINAL  
INNER JOIN
	TBLORDERH_DEV_FINAL H_FINAL
ON
	H_FINAL.SLS_DOC_NO = I_FINAL.SLS_DOC_NO
INNER JOIN
	[10.168.0.57].ISAP.DBO.TBLORDERI PROD
ON	
	I_FINAL.SLS_DOC_NO = PROD.SLS_DOC_NO
AND
	I_FINAL.LINE_NO = PROD.LINE_NO
WHERE 
	PROD.billing_status	 is not null
---Se Respaldan del 01 Enero 2018 al 23 Enero 2019
-------------------------------------------------
TRUNCATE TABLE [TBLORDERH_RESPALDO_PROD]
INSERT INTO [TBLORDERH_RESPALDO_PROD]
SELECT * FROM [10.168.0.57].ISAP.DBO.[TBLORDERH] WHERE CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'

TRUNCATE TABLE [TBLORDERI_RESPALDO_PROD]
INSERT INTO [TBLORDERI_RESPALDO_PROD]
SELECT I.* FROM 
	[10.168.0.57].ISAP.DBO.[TBLORDERH] H 
INNER JOIN 
	[10.168.0.57].ISAP.DBO.[TBLORDERI] I 
ON 
	H.SLS_DOC_NO = I.SLS_DOC_NO 
WHERE 
	CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'
---------------------------------------------------
---BORRAR INFO DE TABLAS DE TBLORDERH Y TBLORDERI
DELETE I FROM 
	[10.168.0.57].ISAP.DBO.[TBLORDERI] I 
INNER JOIN 	
	[10.168.0.57].ISAP.DBO.[TBLORDERH] H 
ON 
	H.SLS_DOC_NO = I.SLS_DOC_NO 
WHERE 
	CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'

DELETE FROM 
	[10.168.0.57].ISAP.DBO.[TBLORDERH] 
WHERE 
	CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'
--------------------------------------------------
---METER LA NUEVA INFO
INSERT INTO [10.168.0.57].ISAP.DBO.[TBLORDERH]
SELECT * FROM tblOrderH_dev_final

INSERT INTO [10.168.0.57].ISAP.DBO.[TBLORDERI]
SELECT * FROM tblOrderI_dev_final
--------------------------------------------------

------------------------------------------------------------------
--ROLLBACK
DELETE I FROM 
	[10.168.0.57].ISAP.DBO.[TBLORDERI] I 
INNER JOIN 	
	[10.168.0.57].ISAP.DBO.[TBLORDERH] H 
ON 
	H.SLS_DOC_NO = I.SLS_DOC_NO 
WHERE 
	CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'

DELETE FROM 
	[10.168.0.57].ISAP.DBO.[TBLORDERH] 
WHERE 
	CUST_PO_DATE BETWEEN '2018-01-01 00:00:00.000' AND '2019-01-22 00:00:00.000'
	

INSERT INTO [10.168.0.57].ISAP.DBO.[TBLORDERH]
SELECT * FROM tblOrderH_RESPALDO_PROD

INSERT INTO [10.168.0.57].ISAP.DBO.[TBLORDERI]
SELECT * FROM tblOrderI_RESPALDO_PROD
--------------------------------------------------------------------